=== maschwie/GIANT/doc/handbuch/giant_vis_style_file.dtd
<!ELEMENT giant_vis_style_file 
  (global_settings, 
   default_node_setting, (node_class_specific_setting)*,
   default_edge_setting, (edge_class_specific_setting)*)>

  <!ELEMENT global_settings EMPTY>
  <!ATTLIST global_settings 
    vis_window_background_color CDATA #REQUIRED
  >
 
  <!ELEMENT default_node_setting (node_attribute)*>
  <!ATTLIST default_node_setting 
    icon         CDATA #REQUIRED
    text_color   CDATA #REQUIRED
    border_color CDATA #REQUIRED
    fill_color   CDATA #REQUIRED
  >

  <!ELEMENT node_class_specific_setting 
    ((node_attribute)*, (node_class)*, (super_node_class)*)>
  <!ATTLIST node_class_specific_setting 
    icon         CDATA #REQUIRED
    text_color   CDATA #REQUIRED
    border_color CDATA #REQUIRED
    fill_color   CDATA #REQUIRED
  >
      
    <!ELEMENT node_attribute EMPTY>
    <!ATTLIST node_attribute 
      attribute_name CDATA #REQUIRED
    >

    <!-- A node class that is affected by this setting. -->
    <!ELEMENT node_class EMPTY>   
    <!ATTLIST node_class
      node_class_name CDATA #REQUIRED
    >
    
    <!ELEMENT super_node_class EMPTY>   
    <!ATTLIST super_node_class
      super_node_class_name CDATA #REQUIRED
    >    
    
  <!ELEMENT default_edge_setting EMPTY>
  <!ATTLIST default_edge_setting
    line_color CDATA                                     #REQUIRED
    text_color CDATA                                     #REQUIRED 
    line_style (continuous_line|dotted_line|dashed_line) #REQUIRED
    show_label (yes|no)                                  #REQUIRED
  >

  <!ELEMENT edge_class_specific_setting ((edge_class)*, (super_edge_class)*)>
  <!ATTLIST edge_class_specific_setting
     line_color CDATA                                     #REQUIRED
     text_color CDATA                                     #REQUIRED
     line_style (continuous_line|dotted_line|dashed_line) #REQUIRED
     show_label (yes|no)                                  #REQUIRED
  > 
        
    <!ELEMENT edge_class EMPTY>
    <!ATTLIST edge_class
      start_node_class CDATA #REQUIRED
      attribute_name   CDATA #REQUIRED
    >
    
    <!ELEMENT super_edge_class EMPTY>
    <!ATTLIST super_edge_class
      super_start_node_class CDATA #REQUIRED
      attribute_name         CDATA #REQUIRED
    >

=== maschwie/GIANT/test/resources/vis_styles/vis_styles_test_set_2/test_vis_style_3.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

  <!-- ................................................................. -->
  <global_settings
    vis_window_background_color="RGB:AA/AA/AA"/> 

  <!-- ................................................................. -->
  <default_node_setting
    icon         = "test_node_icon_default_1.xpm"
    text_color   = "RGB:AA/AA/AA"
    border_color = "RGB:AA/AA/AA"
    fill_color   = "white"> 
     
    <node_attribute attribute_name = "SLoc"/>      
  </default_node_setting>
   
   
  <node_class_specific_setting 
    icon         = "test_node_icon_blue_1.xpm"
    text_color   = "red"
    border_color = "red"
    fill_color   = "red"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
     
    <node_class     node_class_name = "IML_Root"/>
    <node_class     node_class_name = "HPGNode"/>
    <node_class     node_class_name = "OC_Parameter"/>    
        
    <node_class     node_class_name = "TC_Boolean"/>
  </node_class_specific_setting>
  
  
  <node_class_specific_setting 
    icon         = "test_node_icon_blue_1.xpm"
    text_color   = "black"
    border_color = "black"
    fill_color   = "black"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
          
    <node_class     node_class_name = "TC_Boolean"/>      
  </node_class_specific_setting>
      
      
      
  <!-- ................................................................. -->
  <default_edge_setting
    line_color = "black"     
    text_color = "black"     
    line_style = "continuous_line"      
    show_label = "no" />  
      
</giant_vis_style_file>

=== maschwie/GIANT/shared/styles/Default.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

  <!-- ................................................................. -->
  <global_settings
    vis_window_background_color="#FFFFFF"/> 

  <!-- ................................................................. -->
  <default_node_setting
    icon         = "../icons/giant_icon.xpm"
    text_color   = "#000000"
    border_color = "#000000"
    fill_color   = "#C4EDED"> 
     
    <node_attribute attribute_name  = "Parent"/>       
    <node_attribute attribute_name  = "SLoc"/>       
  </default_node_setting>
    
  <node_class_specific_setting 
    icon         = "../icons/IML_Root_icon_1.xpm"
    text_color   = "#000000"
    border_color = "#000000"
    fill_color   = "#50FF50"> 

    <node_attribute attribute_name  = "Parent"/>       
    <node_attribute attribute_name  = "SLoc"/>   
    <node_attribute attribute_name  = "Artificial"/>       

    <node_class node_class_name = "IML_Root"/>  
  </node_class_specific_setting>
  
  
  <node_class_specific_setting 
    icon         = "../icons/test_node_icon_red_1.xpm"
    text_color   = "#FFFFFF"
    border_color = "#000000"
    fill_color   = "#5050FF"> 
    
    <node_attribute attribute_name  = "SLoc"/>   
    <node_attribute attribute_name  = "CF_Next"/>     
    <node_attribute attribute_name  = "CF_Previous"/>   
    <node_attribute attribute_name  = "CF_Basic_Block"/>     
                             
    <super_node_class   super_node_class_name = "Value"/> 
  </node_class_specific_setting>
      
     
  <node_class_specific_setting 
    icon         = "../icons/T_Node_icon_1.xpm"
    text_color   = "#000000"
    border_color = "#000000"
    fill_color   = "#FFD000"> 
    
    <node_attribute attribute_name  = "SLoc"/>   
    <node_attribute attribute_name  = "Namespace_Name"/>     
    <node_attribute attribute_name  = "Type_Size"/>   
                                
    <super_node_class   super_node_class_name = "T_Node"/> 
  </node_class_specific_setting>
  
  <node_class_specific_setting 
    icon         = "../icons/test_node_icon_blue_1.xpm"
    text_color   = "#000000"
    border_color = "#000000"
    fill_color   = "#60FFFF"> 
    
    <node_attribute attribute_name  = "Parent"/>   
    <node_attribute attribute_name  = "SLoc"/>     
    <node_attribute attribute_name  = "Name"/>   
                                
    <super_node_class   super_node_class_name = "O_Node"/> 
  </node_class_specific_setting>

  <!-- ................................................................. -->
  <default_edge_setting
    line_color = "#000000"     
    text_color = "#000000"     
    line_style = "dotted_line"      
    show_label = "no" />  
    
  <edge_class_specific_setting
    line_color = "#FFD000"
    text_color = "#FFD000"
    line_style = "dashed_line"
    show_label = "yes"> 
            
    <super_edge_class
      super_start_node_class = "T_Node"
      attribute_name   = "*" />                    
  </edge_class_specific_setting> 
       
  <edge_class_specific_setting
    line_color = "#FF0000"
    text_color = "#FF0000"
    line_style = "continuous_line"
    show_label = "yes"> 
            
    <edge_class
      start_node_class = "*"
      attribute_name   = "Parent" />                    
  </edge_class_specific_setting> 
                 
</giant_vis_style_file>

=== maschwie/GIANT/doc/handbuch/test_vis_style_5_inheritance.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

  <global_settings
    vis_window_background_color="RGB:20/20/20"/> 

  <default_node_setting
    icon         = "test_node_icon_default_1.xpm"
    text_color   = "black"
    border_color = "black"
    fill_color   = "white"> 
     
  </default_node_setting>
   
  
  <node_class_specific_setting 
    icon         = "test_node_icon_red_1.xpm"
    text_color   = "red"
    border_color = "red"
    fill_color   = "white"> 
    
    <node_attribute attribute_name  = "Type_Size"/> 
    <node_attribute attribute_name  = "SLoc"/> 
                            
    <node_class     node_class_name = "IML_Root"/> 
    <node_class     node_class_name = "HPGNode"/> 
    
    <super_node_class super_node_class_name = "T_Node"/> 
    <super_node_class super_node_class_name = "Prog_Unit"/>   
    
  </node_class_specific_setting>
  
                  
  <default_edge_setting
    line_color = "RGB:00/FF/FF"     
    text_color = "RGB:00/FF/FF"     
    line_style = "dotted_line"      
    show_label = "no" />  
         
  <edge_class_specific_setting
    line_color = "green"
    text_color = "green"
    line_style = "dashed_line"
    show_label = "yes"> 

    <super_edge_class
      super_start_node_class = "Prog_Unit"
      attribute_name   = "Subunits" />   
      
    <super_edge_class
      super_start_node_class = "Op"
      attribute_name   = "*" /> 
                             
  </edge_class_specific_setting>          
  
  <edge_class_specific_setting
    line_color = "blue"
    text_color = "blue"
    line_style = "dotted_line"
    show_label = "yes"> 

  <edge_class
      super_start_node_class = "*"
      attribute_name   = "SLOC" /> 
                             
  </edge_class_specific_setting>   
	
</giant_vis_style_file>

=== maschwie/GIANT/giant/shared/styles/Plain.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

  <!-- ................................................................. -->
  <global_settings
    vis_window_background_color="#FFFFFF"/> 

  <!-- ................................................................. -->
  <default_node_setting
    icon         = "test_node_icon_default_1.xpm"
    text_color   = "#CCCCCC"
    border_color = "#CCCCCC"
    fill_color   = "#FFFFFF"> 
     
    <node_attribute attribute_name = "SLoc"/>      
  </default_node_setting>
   
   
  <node_class_specific_setting 
    icon         = "test_node_icon_blue_1.xpm"
    text_color   = "#0000FF"
    border_color = "#0000FF"
    fill_color   = "#FFFFFF"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
     
    <node_class     node_class_name = "IML_Root"/>
    <node_class     node_class_name = "HPGNode"/>
    <node_class     node_class_name = "OC_Parameter"/>        
    <node_class     node_class_name = "TC_Boolean"/>
  </node_class_specific_setting>
  
  
  <node_class_specific_setting 
    icon         = "test_node_icon_red_1.xpm"
    text_color   = "#FF0000"
    border_color = "#FF0000"
    fill_color   = "#FFFFFF"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
    <node_attribute attribute_name  = "Type_Size"/>        
    <node_class     node_class_name = "TC_Boolean"/>      
  </node_class_specific_setting>
      
      
      

  <!-- ................................................................. -->
  <default_edge_setting
    line_color = "#00FF00"     
    text_color = "#00FF00"     
    line_style = "continuous_line"      
    show_label = "yes" />  
      
</giant_vis_style_file>

=== maschwie/GIANT/giant/test/resources/vis_styles/vis_styles_test_set_default_1/test_vis_style_1_default.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

  <!-- ................................................................. -->
  <global_settings
    vis_window_background_color="RGB:20/20/20"/> 

  <!-- ................................................................. -->
  <default_node_setting
    icon         = "test_node_icon_default_1.xpm"
    text_color   = "RGB:AA/AA/A1"
    border_color = "RGB:AA/AA/A2"
    fill_color   = "RGB:AA/AA/A3"> 
     
    <node_attribute attribute_name = "SLoc"/>      
  </default_node_setting>
   
   
  <node_class_specific_setting 
    icon         = "test_node_icon_blue_1.xpm"
    text_color   = "blue"
    border_color = "blue"
    fill_color   = "white"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
     
    <node_class     node_class_name = "IML_Root"/>
    <node_class     node_class_name = "HPGNode"/>
    <node_class     node_class_name = "OC_Parameter"/>        
    <node_class     node_class_name = "TC_Boolean"/>
  </node_class_specific_setting>
  
  
  <node_class_specific_setting 
    icon         = "test_node_icon_red_1.xpm"
    text_color   = "red"
    border_color = "red"
    fill_color   = "white"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
    <node_attribute attribute_name  = "Type_Size"/>   
         
    <node_class     node_class_name = "TC_Boolean"/>      
  </node_class_specific_setting>
      
      
      

  <!-- ................................................................. -->
  <default_edge_setting
    line_color = "green"     
    text_color = "green"     
    line_style = "continuous_line"      
    show_label = "yes" />  
      
</giant_vis_style_file>

=== maschwie/GIANT/giant/test/resources/vis_styles/vis_styles_test_set_2/test_vis_style_4_edges.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

  <!-- ................................................................. -->
  <global_settings
    vis_window_background_color="RGB:20/20/20"/> 

  <!-- ................................................................. -->
  <default_node_setting
    icon         = "test_node_icon_default_1.xpm"
    text_color   = "RGB:AA/AA/AA"
    border_color = "RGB:AA/AA/AA"
    fill_color   = "white"> 
     
    <node_attribute attribute_name = "SLoc"/>      
  </default_node_setting>
   
   
  <node_class_specific_setting 
    icon         = "test_node_icon_blue_1.xpm"
    text_color   = "blue"
    border_color = "blue"
    fill_color   = "white"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
     
    <node_class     node_class_name = "IML_Root"/>
    <node_class     node_class_name = "HPGNode"/>
    <node_class     node_class_name = "OC_Parameter"/>        
    <node_class     node_class_name = "TC_Boolean"/>
  </node_class_specific_setting>
  
  
  <node_class_specific_setting 
    icon         = "test_node_icon_red_1.xpm"
    text_color   = "red"
    border_color = "red"
    fill_color   = "white"> 
    
    <node_attribute attribute_name  = "SLoc"/>    
    <node_attribute attribute_name  = "Type_Size"/>        
    <node_class     node_class_name = "TC_Boolean"/>      
  </node_class_specific_setting>
      
      
      
  <!-- ................................................................. -->
  <default_edge_setting
    line_color = "RGB:AA/AA/A1"     
    text_color = "RGB:AA/AA/A2"     
    line_style = "continuous_line"      
    show_label = "no" />  
      
 
  <edge_class_specific_setting
    line_color = "blue"
    text_color = "blue"
    line_style = "dotted_line"
    show_label = "yes"> 
   
    <edge_class
      start_node_class = "Routine_Call"
      attribute_name   = "*" />      
     
    <edge_class
      start_node_class = "*"
      attribute_name   = "CF_Next" />            
  </edge_class_specific_setting>
  
  <edge_class_specific_setting
    line_color = "green"
    text_color = "green"
    line_style = "dashed_line"
    show_label = "no"> 
   
    <edge_class
      start_node_class = "Array_LR_Conversion"
      attribute_name   = "CF_Next" />              
  </edge_class_specific_setting> 
      
</giant_vis_style_file>

=== maschwie/GIANT/giant/src/config/giant_vis_style.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_vis_style_file
  SYSTEM "giant_vis_style_file.dtd">

<giant_vis_style_file>

   <!-- ................................................................. -->
   <global_settings
      vis_window_background_color="RBG:AA/AA/AA"/> 

   <!-- ................................................................. -->

   <default_node_setting
      icon         = "./my_test_icon.xpm"
      text_color   = "RGB:AA/AA/AA"
      border_color = "RGB:AA/AA/AA"
      fill_color   = "RGB:AA/AA/AA"> 

      <node_attribute attribute_name = "Attribute_1" />
      <node_attribute attribute_name = "Attribute_2" />    
      <node_attribute attribute_name = "Attribute_3" />        
      <node_attribute attribute_name = "Attribute_4" />   
   </default_node_setting>

   <node_class_specific_setting
      icon         = "./my_test_icon.xpm"
      text_color   = "RGB:AA/AA/AA"
      border_color = "RGB:AA/AA/AA"
      fill_color   = "RGB:AA/AA/AA">

      <node_attribute attribute_name = "Attribute_1" />
      <node_attribute attribute_name = "Attribute_2" />   

      <!-- Only the following node classes are affected by the
           settings inside the <node_class_specific_setting> node -->
      <node_class node_class_name = "Dagobert Duck" />
      <node_class node_class_name = "Daisy Duck" />   
      <node_class node_class_name = "Gustav Gans" />   
   </node_class_specific_setting> 

   <!-- ................................................................. -->
   <default_edge_setting
      line_color = "RGB:AA/AA/AA"     
      text_color = "RGB:AA/AA/AA"     
      line_style = "dotted_line"
      show_label = "yes" />  

   <edge_class_specific_setting
      line_color = "RGB:AA/AA/AA"     
      text_color = "RGB:AA/AA/AA"     
      line_style = "dotted_line"
      show_label = "yes" >
       
      <!-- Edge classes that are affected by this setting -->
      <edge_class
         start_node_class = "Dagobert" attribute_name = "Anzahl Federn" />
      <edge_class
         start_node_class = "Daisy" attribute_name = "*" />
      <edge_class
         start_node_class = "*" attribute_name = "IQ Edge" />
   </edge_class_specific_setting> 

</giant_vis_style_file>
