=== maschwie/GIANT/doc/handbuch/giant_config_file.dtd
<!ELEMENT giant_config_file (absolute_path_root?, (setting)*)>

  <!ELEMENT absolute_path_root EMPTY>
  <!ATTLIST absolute_path_root
    root_directory  CDATA #REQUIRED
  >

  <!ELEMENT setting EMPTY>
  <!ATTLIST setting
    name   CDATA #REQUIRED
    value  CDATA #REQUIRED
  >

=== maschwie/GIANT/etc/global_config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_config_file 
  SYSTEM "giant_config_file.dtd">

<giant_config_file>

  <!-- <absolute_path_root root_directory  = "resources_dir" /> -->
  			
  <!-- Required Config Settings -->  
  
  <setting name="Resources_Directory" value="../shared" />
  
  <setting name="Icon_For_Node_Annotations" value="../shared/icons/document.xpm" />
  
  <setting name="Current_Selection_Highlight_Color" value="#AAAAAA" />
					  
  <setting name="Selection_Highlight_Color_1" value="#FF0000" />
  <setting name="Selection_Highlight_Color_2" value="#00FF00"/>
  <setting name="Selection_Highlight_Color_3" value="#0000FF" />
					  
  <setting name="IML_Subgraph_Highlight_Color_1" value="#00FFFF" />
  <setting name="IML_Subgraph_Highlight_Color_2" value="#FF00FF" />
  <setting name="IML_Subgraph_Highlight_Color_3" value="#FFFF00" />

  <setting name="Editor.Source" value="/usr/bin/emacs +%l %f" />
  <!-- This setting only works for emacs 21 -->
  <!-- <setting name="Editor.Source" value="/usr/bin/emacs +%l:%c %f" /> -->

  <setting name="GSL.Include_Path" value="../shared/gsl" />

  <!-- Settings for scripts in menus -->
  <setting name="GSL.No_Param" value="Open Entire Graph:Open HPG:Search For Routine:Create Complete Subgraph" />
  <setting name="GSL.No_Param_Context" value="" />
  <setting name="GSL.Node_Id_Param" value="Get Adjacent Nodes:Get Statements:Trace Function Call" />
  <setting name="GSL.Edge_Id_Param" value="" />
  <setting name="GSL.Subgraph_Param" value="To Window" />
  <setting name="GSL.Selection_Param" value="Get Successors" />

</giant_config_file>

=== maschwie/GIANT/test/resources/gsl_support_test_data/test_config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_config_file 
  SYSTEM "giant_config_file.dtd">

<giant_config_file>

  <absolute_path_root root_directory  = "." />
 
  <!-- Some Free Config Settings -->
  <setting name="Reiche_Ente" value="Dagobert Duck" />
  <setting name="Schlaue_Ente" value="Daniel Duesentrieb" />
  <setting name="Arme_Ente" value="Donald Duck" />
			
  <!-- Required Config Settings -->  
  
  <setting name="Resources_Directory" value="." />
  
  <!-- Relative Paths in all config files are regarded as relative -->
  <!-- towards the "Resources_Directory" if you change the standard -->
  <!-- Resource dirctory in a user defined config file then -->
  <!-- all relative paths in the standard config file of giant will -->
  <!-- also be regarded as realtive towards this path -->
  <setting name="Icon_For_Node_Annotations" value="./test_bild.xpm" />
  
  <setting name="Actual_Selection_Highlight_Color" value="RGB:00/00/00" />
					  
  <setting name="Selection_Highlight_Color_1" value="RGB:FF/00/00" />
  <setting name="Selection_Highlight_Color_2" value="RGB:00/FF/00"/>
  <setting name="Selection_Highlight_Color_3" value="RGB:00/00/FF" />
					  
  <setting name="IML_Subgraph_Highlight_Color_1" value="RGB:00/FF/FF" />
  <setting name="IML_Subgraph_Highlight_Color_2" value="RGB:FF/00/FF" />
  <setting name="IML_Subgraph_Highlight_Color_3" value="RGB:FF/FF/00" />  
  
  <setting name="GSL.Include_Path" 
           value="./gsl_include_dir_1:./gsl_include_dir_2" />    
</giant_config_file>

=== maschwie/GIANT/doc/handbuch/global_config.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_config_file 
  SYSTEM "giant_config_file.dtd">

<giant_config_file>

  <absolute_path_root root_directory  = "resources_dir" />
  
  <setting name="Resources_Directory" value=".." />
  
  <setting name  = "Icon_For_Node_Annotations" 
           value = "annotations_icon_user.xpm" />
  
  <setting name="Actual_Selection_Highlight_Color" value="RGB:00/00/80" />
					  
  <setting name="Selection_Highlight_Color_1" value="RGB:FF/00/00" />
  <setting name="Selection_Highlight_Color_2" value="RGB:00/FF/00"/>
  <setting name="Selection_Highlight_Color_3" value="RGB:00/00/FF" />
					  
  <setting name="IML_Subgraph_Highlight_Color_1" value="RGB:00/FF/FF" />
  <setting name="IML_Subgraph_Highlight_Color_2" value="RGB:FF/00/FF" />
  <setting name="IML_Subgraph_Highlight_Color_3" value="RGB:FF/FF/00" />

  <setting name="GSL.Include_Path" value="./gsl" />  
</giant_config_file>
