=== maschwie/GIANT/doc/handbuch/giant_class_set_file.dtd
<!ELEMENT giant_class_set_file 
  (associated_node_classes, associated_edge_classes)>

  <!ELEMENT associated_node_classes ((node_class)*, (super_node_class)*)>

    <!ELEMENT node_class EMPTY>   
    <!ATTLIST node_class
      node_class_name CDATA #REQUIRED
    >
    
    <!ELEMENT super_node_class EMPTY>   
    <!ATTLIST super_node_class
      super_node_class_name CDATA #REQUIRED
    > 

  <!ELEMENT associated_edge_classes ((edge_class)*, (super_edge_class)*)>

    <!ELEMENT edge_class EMPTY>
    <!ATTLIST edge_class
      start_node_class CDATA #REQUIRED
      attribute_name   CDATA #REQUIRED
    >
    
    <!ELEMENT super_edge_class EMPTY>
    <!ATTLIST super_edge_class
      super_start_node_class CDATA #REQUIRED
      attribute_name         CDATA #REQUIRED
    >

=== maschwie/GIANT/src/config/class_sets.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_class_set_file 
  SYSTEM "giant_class_set_file.dtd">

<giant_class_set_file>

  <!-- All node classes being a member of the class set -->
  <associated_node_classes>
  
    <node_class node_class_name="Donald" />
    <node_class node_class_name="Dagobert" />
    <node_class node_class_name="Daisy" />

  </associated_node_classes>
  
  <!-- All edge classes being a member of the class set -->
  <associated_edge_classes>
 
    <edge_class start_node_class="Dagobert" attribute_name="Vermoegen" />	
    <edge_class start_node_class="Donald" attribute_name="*" />	
    <edge_class start_node_class="*" attribute_name="Anzahl_Federn" />	

  </associated_edge_classes>
 

</giant_class_set_file>

=== maschwie/GIANT/doc/handbuch/class_set_5_inheritance.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE giant_class_set_file 
  SYSTEM "giant_class_set_file.dtd">

<giant_class_set_file>

  <!-- All node classes being a member of the class set -->
  <associated_node_classes>
  
    <super_node_class     super_node_class_name = "T_Node"/>                      
    <super_node_class     super_node_class_name = "Prog_Unit"/>  

  </associated_node_classes>
  
  <!-- All edge classes being a member of the class set -->
  <associated_edge_classes>
 
    <super_edge_class
      super_start_node_class = "Prog_Unit"
      attribute_name         = "Subunits" />        
    <super_edge_class
      super_start_node_class = "Op"
      attribute_name         = "*" /> 	      
    <super_edge_class
      super_start_node_class = "Return_Statement"
      attribute_name         = "*" /> 	

  </associated_edge_classes>
 

</giant_class_set_file>
